### ISSUE TITLE
"stof_doctrine_extensions.uploadable.validate_writable_directory" must be defined.

### ISSUE THREAD

**Issue by neoshadybeat** [stof/StofDoctrineExtensionsBundle#206]
I've updated the bundle today, and on pro environment, throw that when I try to clean cache, I haven't found any doc about this, and I try to define this on my config.yml and still gives the error

Thanks a lot

**Comment by velikanov** [comment]
:+1: worked for me
strange behaviour

**Comment by bocharsky-bw** [comment]
@sescandell This is a workaround. I think issue should be reopen and fixed if not yet

**Comment by bocharsky-bw** [comment]
Fixed in https://github.com/stof/StofDoctrineExtensionsBundle/pull/187

**Comment by baldasso** [comment]
The issue still exists.
 Thanks @sescandell your solution still works too.
